<a href="https://colab.research.google.com/github/thq1995/AI_Learning/blob/main/KNN/1_KNN_IRIS_1D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets
import pandas as pd

In [2]:
!gdown 1dd4uRTOyouYWZcloYhKQBAxAar5NEpJv

Downloading...
From: https://drive.google.com/uc?id=1dd4uRTOyouYWZcloYhKQBAxAar5NEpJv
To: /content/iris_1D.csv
100% 67.0/67.0 [00:00<00:00, 177kB/s]


In [3]:
data = pd.read_csv('iris_1D.csv')
data

Petal_Length  Label
0           1.4    0.0
1           1.0    0.0
2           1.5    0.0
3           3.1    1.0
4           3.8    1.0
5           4.1    1.0

In [4]:
# get x
x_data = data['Petal_Length'].to_numpy()
x_data = x_data.reshape(6, 1)
print(x_data)

[[1.4]
 [1. ]
 [1.5]
 [3.1]
 [3.8]
 [4.1]]


In [5]:
# get y
y_data = data['Label'].to_numpy()
print(y_data)

[0. 0. 0. 1. 1. 1.]


In [6]:
# unknown input
x_test = [[2.4]]

### Way 1

In [7]:
# get model
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_data, y_data)

KNeighborsClassifier(n_neighbors=3)

In [8]:
y_pred = classifier.predict(x_test)
print(y_pred)

[0.]


### Way 2

In [9]:
# get model
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=6)
classifier.fit(x_data, y_data)

KNeighborsClassifier(n_neighbors=6)

In [10]:
y_pred = classifier.kneighbors(x_test)
print(y_pred)

(array([[0.7, 0.9, 1. , 1.4, 1.4, 1.7]]), array([[3, 2, 0, 1, 4, 5]]))


In [11]:
classifier.classes_[classifier._y[3]]

1.0

In [13]:
print(classifier.classes_)

[0. 1.]
