<a href="https://colab.research.google.com/github/thq1995/AI_Learning/blob/main/KNN/4_KNN_IRIS_2D_UsingScaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## in cm

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets
import pandas as pd
from sklearn.preprocessing import StandardScaler

!gdown 1D-L1M4LkmzxvpiVl3GSj3SD3Ge8Za9TX

data = pd.read_csv('iris_2D.csv')

# get x
x_data = data[['Petal_Length', 'Petal_Width']].to_numpy()
x_data = x_data.reshape(6, 2)
print(x_data)

# get y
y_data = data['Label'].to_numpy()
print(y_data)

Downloading...
From: https://drive.google.com/uc?id=1D-L1M4LkmzxvpiVl3GSj3SD3Ge8Za9TX
To: /content/iris_2D.csv
100% 102/102 [00:00<00:00, 198kB/s]
[[1.4 0.2]
 [1.3 0.4]
 [1.4 0.3]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]]
[0. 0. 0. 1. 1. 1.]


In [8]:
scaler = StandardScaler()
scaler.fit(x_data)

x_data = scaler.transform(x_data)
print(x_data)

[[-0.94942533 -1.16756479]
 [-1.02063223 -0.7554831 ]
 [-0.94942533 -0.96152395]
 [ 0.90195406  0.48076197]
 [ 1.40040236  1.30492536]
 [ 0.61712646  1.09888451]]


In [11]:
# get model
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=6)
classifier.fit(x_data, y_data)

# unknown input
x_test = [[2.6, 0.7]]
x_test = scaler.transform(x_test)
print(x_test)

y_pred = classifier.kneighbors(x_test)
print(y_pred)

y_predict = classifier.predict(x_test)
print(y_predict)

[[2.6 0.7]]
(array([[1.34349142, 1.71214057, 2.02259643, 3.90223126, 3.91906647,
        4.01076282]]), array([[4, 3, 5, 1, 2, 0]]))
[0.]


## in mm

In [12]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets
import pandas as pd
from sklearn.preprocessing import StandardScaler

!gdown 1bKSvPHc9bcLWcMxQieLBwzl9740zRgFw

data = pd.read_csv('iris_2D_mm.csv')

# get x
x_data = data[['Petal_Length', 'Petal_Width']].to_numpy()
x_data = x_data.reshape(6, 2)
print(x_data)

# get y
y_data = data['Label'].to_numpy()
print(y_data)

Downloading...
From: https://drive.google.com/uc?id=1bKSvPHc9bcLWcMxQieLBwzl9740zRgFw
To: /content/iris_2D_mm.csv
100% 105/105 [00:00<00:00, 410kB/s]
[[ 1.4  2. ]
 [ 1.3  4. ]
 [ 1.4  3. ]
 [ 4.  10. ]
 [ 4.7 14. ]
 [ 3.6 13. ]]
[0. 0. 0. 1. 1. 1.]


In [13]:
scaler = StandardScaler()
scaler.fit(x_data)

x_data = scaler.transform(x_data)
print(x_data)

[[-0.94942533 -1.16756479]
 [-1.02063223 -0.7554831 ]
 [-0.94942533 -0.96152395]
 [ 0.90195406  0.48076197]
 [ 1.40040236  1.30492536]
 [ 0.61712646  1.09888451]]


In [15]:
# get model
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=6)
classifier.fit(x_data, y_data)

# unknown input
x_test = [[2.6, 7.0]]
x_test = scaler.transform(x_test)
print(x_test)

y_pred = classifier.kneighbors(x_test)
print(y_pred)

[[-0.09494253 -0.13736056]]
(array([[1.11309338, 1.17297838, 1.18717569, 1.33845493, 1.42665488,
        2.07755746]]), array([[1, 3, 2, 0, 5, 4]]))
