<a href="https://colab.research.google.com/github/thq1995/AI_Learning/blob/main/KNN/5_BoW_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import numpy as np

In [35]:
vectorizer = CountVectorizer()
corpus = ["góp gió gặt bão",
          "có làm mới có ăn",
          "đất lành chim đậu",
          "ăn cháo đá bát",
          "gậy ông đập lưng ông",
          "qua cầu rút ván"]
X = vectorizer.fit_transform(corpus)

In [36]:
print(f"X shape: {X.shape}")
print(f'X: {X.toarray()}')

X shape: (6, 23)
X: [[0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1]
 [1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 2 0 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]]


In [63]:
x_test = vectorizer.transform(['có làm mới có ăn']).toarray()
x_test

array([[0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0]])

In [64]:
y_data = np.array([1, 1, 1, 0, 0, 0])
y_data

array([1, 1, 1, 0, 0, 0])

In [65]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=6)
classifier.fit(X.toarray(), y_data)

y_pred = classifier.kneighbors(x_test)
print(y_pred)





(array([[0.        , 3.        , 3.31662479, 3.31662479, 3.31662479,
        3.74165739]]), array([[1, 3, 0, 2, 5, 4]]))


In [66]:
y_pred = classifier.predict(x_test)
y_pred

array([0])